[project]
name = "ai-email-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "google-api-python-client>=2.200.0",
    "google-auth-httplib2>=0.4.2",
    "google-auth-oauthlib>=1.4.1",
    "langchain-openai>=1.6.2",
    "openai>=3.14.1",
    "pandas>=3.0.5",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "sendgrid>=6.12.5",
    "uvicorn>=0.53.0",
]
